# Generated by Django 4.1.7 on 2023-03-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='adcd', upload_to='testimonials'),
            preserve_default=False,
        ),
    ]
