# Generated by Django 4.1.7 on 2023-03-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_testimonial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(default='Software Engineer', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='NISHMAL', max_length=225),
        ),
    ]
