# Generated by Django 4.1.7 on 2023-03-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_testimonial_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
